apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app01
  template:
    metadata:
      labels:
        app: sample-app01
    spec:
      containers:
      - name: sample-app01
        image: nginx:stable-alpine3.17
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app01-svc
spec:
  type: ClusterIP
  selector:
    app: sample-app01
  ports:
  - port: 8080
