IMAGE_NAME = "ubuntu/bionic64"
K8S_NODES_NUMBER = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2024
        vb.cpus = 2
    end

    config.vm.define "k8s_master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.20.20"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            #compatibility_mode = "2.0"
            ansible.playbook = "k8s-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.20.20",
            }
        end
    end

    (1..K8S_NODES_NUMBER).each do |i|
        config.vm.define "k8s_node_#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.20.#{i + 20}"
            node.vm.hostname = "k8s-node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "k8s-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.20.#{i + 20}",
                }
            end
        end
    end
end
